---
stages:
- name: 'Deploy to Cloud Foundry'
  inputs:
  - type: git
    branch: master
    service: app-repo
  triggers:
  - type: commit
  properties:
  - name: CLOUDANT_SVC_NAME
    value: how-do-i-cloudantNoSQLDB
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      # Push app
      cf create-service cloudantNoSQLDB Lite ${CLOUDANT_SVC_NAME}
      cf push "${CF_APP_NAME}"   
